Validation des précédents commit
yguitton/CP-Seeker pull request #47
Opened 2024-03-29 10:23 UTC by DamienCode404

- [ ]  Réponse à l'Issue : #38
- [ ]  Réponse à l'Issue : #39
- [ ]  Réponse à l'Issue : #40
- [ ]  Réponse à l'Issue : #41

2024-04-22 13:25 UTC, jsaintvanne requested changes

2024-04-22 13:25 UTC, jsaintvanne commented on server/export_function.R
> -  library(openxlsx)
Ca fonctionne en enlevant le chargement de la librairie ici ? Tu l'a ajoutée avant du coup c'est ça ?

2024-04-22 14:17 UTC, DamienCode404 commented on data/create_database.sql
Utilisation d'une clé étrangère d'une table déjà nommée "project". L'identifiant sert à ne garder que les dernières informations de chaque déconvolution par séquence (identifiant unique). Modification de la structure de la base de données dans un prochain commit.

2024-04-22 14:26 UTC, DamienCode404 commented on server.R
> +shiny::observeEvent(input$open_doc, {
Ajout d'un commit pour l'explication de cet observeEvent avec un commentaire.

2024-04-22 14:34 UTC, DamienCode404 commented on server/chem_func.R
Ces fonctions sont des tests pour la librairie Rcpp. Comme ces calculs sont assez simples, ces deux fonctions servent de test pour savoir si le fichier dll avec les fonctions C++ exportés ont bien été chargés dans l'environnement RShiny.
Pour le moment, je n'arrive pas à les charger dans l'environnement pour remplacer les fonctions ppm_to_da et da_to_ppm codés au-dessus en R. C'est pour cela qu'elles restent commentées.

`// Call Rcpp Function (Test)`

2024-04-22 14:44 UTC, DamienCode404 commented on server/export_function.R
> -  library(openxlsx)
Le code présent dans le fichier manager.R présente parcours toutes les librairies et les chargent dans l'environnement avec `library(names(pkgs)[i], character.only = TRUE)`

```
print("ensuring packages dependencies ...")
utils::setWinProgressBar(pb, 0, label = "Ensuring package dependencies ...")  
for (i in seq_along(pkgs)) {
	utils::setWinProgressBar(pb,
		value = i / (length(pkgs) + 1),
		label = sprintf("Loading package - %s", pkgs[i]))
	if(ensure(pkgs[i], names(pkgs)[i], pb) == FALSE) stop(sprintf(
		"%s is not founded or version is incorrect", names(pkgs)[i]))
	else {
		library(names(pkgs)[i], character.only = TRUE)
		print(sprintf("%s loaded", names(pkgs)[i]))
	}
}
```

2024-04-22 15:07 UTC, DamienCode404 commented on server/export_function.R
> +        openxlsx::writeData(wb, sheet, config$appname, startRow = 1)
config$appname est bien présent dans toutes les fonctions d'export. Elles n'ont été ajoutées que pour les deux fonctions qui n'avait pas, PCOs et PXAs. Les trois autres avaient déjà la variable de présente.

Message de Ronan dans l'issue #40 : 
La cellule A1 des onglets de fichiers contient bien le numéro de version de CP-Seeker pour le template PCAs, mais il n'est pas précisé pour les templates PCOs et PXAs. A corriger.

2024-04-23 06:12 UTC, jsaintvanne approved these changes

2024-04-23 06:13 UTC, merged